apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: elastic-operator-crds
  namespace: elastic-system
spec:
  interval: 30m
  chart:
    spec:
      chart: eck-operator-crds
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: monitoring
      interval: 12h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
