apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:HOIQSFbnFGM=,iv:dIDLR94B3wUuZjypi9e5//5lqJnFi8rBUy0myctvWlY=,tag:W5ofLjjy1bJDPFe5B/AhBQ==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:x6Pz565+a9EO/jNgY48aEg==,iv:4Q5kNxy1FtdoQDD8sCEXwndNYURTBU03C2n3EUts0HE=,tag:2Uh8Qx+CViBDPiwWw5eBuw==,type:str]
kind: Secret
metadata:
    name: linkding-container-env
sops:
    age:
        - recipient: age1vz35u62u63z2delvkwz0ese7t2msuk5q76la025dste7s230jg3q3tn6dt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1blNCNFZ6R20xaU8vU0N4
            eUIzZXpwdlBzMzJKdldGV0kxUWp4UnZQQ21BCkQ3S2VVQ0hwaElLdkU4STN5V0Ex
            Vjk1dEpHUk40SlM5dDAwQzd0dnJZT0kKLS0tIDliTTYzakZYa25uZGc1Qm1uUFJw
            MHEva2RIM2JoUWdwYUNkL1FZdkZqSEkK/2XeCjMVz3R3NeQRhDIzaqak5lMbij+Y
            er8eGbuvYvHCXLrdlVLZfk9vjzXA/QQFmNMq0K9PmZlX6bTC0K9srg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-01T21:30:59Z"
    mac: ENC[AES256_GCM,data:CiGUCYVqre+Y92pyu5gjM2PzdcRNcWlAJPEbN2SulfRZgVlkd+QHvyhY2FNPgCMrI4XUXtIezVW0dWFVH+aEuyg+NLOMfbIdSyJnu1ViA1PxF/H8Fejhec7o/3Rw3/e5VDXQV2MQZ+sEpcNqN8T772hS8nTiufnZJ3Tei+hzDXs=,iv:hHeuPtWT3ajxCCfrXrVv+wVkmT4DRgUGWzP4NfbIpOU=,tag:K3bLKXhZ7+ZwP6ejM/sTLA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
