apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-controllers
  namespace: flux-system
spec:
  interval: 10m0s
  # Depends on the flux-system kustomization to ensure the GitRepository is ready
  # dependsOn:
  #   - name: flux-system
  retryInterval: 1m0s
  timeout: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./monitoring/controllers/staging
  prune: true

---

# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: monitoring-configs
#   namespace: flux-system
# spec:
#   interval: 10m0s
#   # Depends on the flux-system kustomization to ensure the GitRepository is ready
#   # dependsOn:
#   #   - name: flux-system
#   retryInterval: 1m0s
#   timeout: 5m0s
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#   path: ./monitoring/configs/staging
#   prune: true