apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: es-kb-quickstart
  namespace: elastic-stack
spec:
  interval: 30m
  chart:
    spec:
      chart: eck-stack
      # optionally pin chart version once you pick one
      # version: "0.17.0"
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: monitoring
      interval: 12h
  # optional, but often useful for ECK CRDs & drift behaviour, mirroring your Prom setup
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  driftDetection:
    mode: enabled
  values:
    # minimal quickstart: rely on chart defaults (ES + Kibana)
    # you can later add:
    # eck-elasticsearch:
    #   nodeSets:
    #     - name: default
    #       count: 3
    # eck-kibana:
    #   http:
    #     service:
    #       spec:
    #         type: LoadBalancer
